name: hi
options:
  bundleIdPrefix: com.app
  deploymentTarget:
    iOS: "16.0"
packages:
  Crypto:
    url: https://github.com/apple/swift-crypto.git
    from: 3.0.0
targets:
  hi:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: Crypto
        product: Crypto
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.app.toanbakhi
        PRODUCT_NAME: hi
        INFOPLIST_KEY_CFBundleDisplayName: hi
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        GENERATE_INFOPLIST_FILE: "YES"
        CODE_SIGN_STYLE: Automatic
